#!/usr/bin/env python3
import sys

from config.create_credentials import setup
from src.calendar_manager import CalendarManager


def execute_from_command_line(argv):
    if argv[1] == 'setup':
        setup()
    else:
        manager = CalendarManager(argv)
        manager.execute()


if __name__ == '__main__':
    execute_from_command_line(sys.argv)
